language: swift
osx_image: xcode10.1
xcode_project: CucumberSwift.xcodeproj # path to your xcodeproj folder
xcode_scheme: CucumberSwift
xcode_destination: platform=iOS Simulator,name=iPhone 8
if: tag IS blank
deploy:
  provider: script
  script: carthage update --platform iOS && ./deploy_pod.sh
  on:
    branch: master
