name: Release

on:
  release:
    types: [ published ]

jobs:
  print:
    runs-on: macos-latest
    steps:
      - name: Cocoapods Release
        run: |
          pod repo add-cdn trunk 'https://cdn.cocoapods.org/'
          pod trunk push CucumberSwift.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}